// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uajdrfwhfkfbwzgtixtk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVhamRyZndoZmtmYnd6Z3RpeHRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NTk2NjksImV4cCI6MjA2MDEzNTY2OX0.x50quc-lHAbMF7Fuse_P3FbKs2nlZTqSulK9SECL5ho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);