[build]
  base = "pizza-byte-inventory-main"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Handle Single Page Application routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 